name: Build GitHub Pages
on:
  push:
    branches:
      - pages-site
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
 
jobs:
  build_mkdocs:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: git checkout pages-site
      - run: pip install \
            mkdocs
      - run: mkdocs gh-deploy --config-file mkdocs.yml --force
